# Generated by Django 4.2.7 on 2025-12-27 12:12

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('medium_url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('tags', models.CharField(help_text='Comma-separated list of tags', max_length=300)),
                ('featured', models.BooleanField(default=False)),
                ('published_date', models.DateField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('business', 'Business'), ('personal_development', 'Personal Development'), ('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('other', 'Other')], default='technical', max_length=50)),
                ('goodreads_url', models.URLField()),
                ('notes_url', models.URLField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('review', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Review')),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('databases', 'Databases & Storage Systems'), ('systems', 'Systems & Performance'), ('ai', 'AI & Machine Learning'), ('distributed', 'Distributed Systems'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=50)),
                ('paper_url', models.URLField()),
                ('notes_url', models.URLField(blank=True, null=True)),
                ('summary', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Summary')),
                ('key_insights', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Key Insights')),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Neha Pandey', max_length=100)),
                ('title', models.CharField(default='Senior Software Engineer', max_length=200)),
                ('bio', django_ckeditor_5.fields.CKEditor5Field(help_text="This is your 'About Me' section content", verbose_name='Bio')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('medium_url', models.URLField(blank=True)),
                ('resume_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('github_url', models.URLField()),
                ('live_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('technologies', models.CharField(help_text='Comma-separated list of technologies', max_length=500)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Neha Pandey | Portfolio', max_length=100)),
                ('meta_description', models.TextField(default='Senior Software Engineer with 5+ years of experience')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('footer_text', models.CharField(default='All rights reserved.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='StudyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=200)),
                ('book_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description')),
                ('book_cover_url', models.URLField(blank=True, help_text='URL to book cover image')),
                ('total_chapters', models.IntegerField(default=0)),
                ('completed_chapters', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('planned', 'Planned')], default='planned', max_length=20)),
                ('notes_url', models.URLField(blank=True, help_text='Link to detailed notes')),
                ('code_examples_url', models.URLField(blank=True, help_text='Link to code examples')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='portfolio.studynote')),
            ],
            options={
                'ordering': ['study_note', 'order', 'chapter_number'],
                'unique_together': {('study_note', 'chapter_number')},
            },
        ),
    ]
