# Generated by Django 4.2.7 on 2025-12-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='key_insights',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(help_text="This is your 'About Me' section content"),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studychapter',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studynote',
            name='book_description',
            field=models.TextField(blank=True),
        ),
    ]
