# Generated by Django 4.2.7 on 2025-12-27 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_blogpost_description_alter_book_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Technical Consultation', 'Career Advice'", max_length=100)),
                ('description', models.TextField(help_text='What this appointment is for')),
                ('duration', models.IntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '1 hour'), (90, '1.5 hours'), (120, '2 hours')], default=30)),
                ('calendly_event_type', models.CharField(blank=True, help_text='Calendly event type URL slug', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price in USD (0 for free)', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='calendly_url',
            field=models.URLField(blank=True, help_text='Your Calendly scheduling link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_calendar_id',
            field=models.CharField(blank=True, help_text='Your Google Calendar ID for appointments', max_length=200),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('purpose', models.TextField(help_text='What would you like to discuss?')),
                ('preferred_date', models.DateTimeField(blank=True, null=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('calendly_event_id', models.CharField(blank=True, max_length=200)),
                ('google_meet_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.appointmenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
