# Generated by Django 4.2.7 on 2025-12-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_appointmenttype_profile_calendly_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Python', 'Django', 'AWS'", max_length=100)),
                ('category', models.CharField(choices=[('languages', 'Programming Languages'), ('frameworks', 'Frameworks & Libraries'), ('databases', 'Databases'), ('cloud_devops', 'Cloud & DevOps'), ('tools', 'Tools & Technologies'), ('other', 'Other')], default='languages', max_length=50)),
                ('proficiency_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=3, help_text='Your skill level (1-4)')),
                ('years_experience', models.IntegerField(blank=True, help_text='Years of experience (optional)', null=True)),
                ('is_featured', models.BooleanField(default=True, help_text='Show on homepage')),
                ('order', models.IntegerField(default=0, help_text='Display order within category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
    ]
