# Generated by Django 4.2.7 on 2025-12-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newsletter_url',
            field=models.URLField(blank=True, help_text='LinkedIn newsletter or other newsletter URL'),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, help_text="DevIcon class (e.g., 'devicon-python-plain', 'devicon-django-plain')", max_length=100),
        ),
    ]
