# Generated by Django 4.2.7 on 2025-12-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_profile_newsletter_url_skill_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newsletter_description',
            field=models.TextField(blank=True, help_text='Brief description of your newsletter content'),
        ),
        migrations.AddField(
            model_name='profile',
            name='newsletter_title',
            field=models.CharField(blank=True, help_text="Newsletter title (e.g., 'Tech Insights Weekly')", max_length=200),
        ),
    ]
